# Dockerfile for Flask Development
FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    playwright install --with-deps

EXPOSE 5001

CMD ["python", "app.py"]
